version: '3.8'

services:
  # --- BANCO DE DADOS ---
  postgres:
    image: postgres:13
    container_name: airflow_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  # --- DATA LAKE (MinIO) ---
  minio:
    image: minio/minio:latest
    container_name: datalake_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  # --- AIRFLOW ---
  airflow-webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      - postgres
      - minio
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # CORREÇÃO DOS LOGS (Request URL missing http)
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW__CORE__HOSTNAME_CALLABLE=airflow.utils.net.get_host_ip_address
      # CONFIGURAÇÕES SPARK/JAVA
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - SPARK_OPTS=--jars /home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/hadoop-aws-3.3.4.jar,/home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/aws-java-sdk-bundle-1.12.262.jar
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./temp_cnpj:/tmp/cnpj
      - ./hadoop-aws-3.3.4.jar:/home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/hadoop-aws-3.3.4.jar
      - ./aws-java-sdk-bundle-1.12.262.jar:/home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/aws-java-sdk-bundle-1.12.262.jar
    command: standalone

  # --- SPARK MASTER ---
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  # --- SPARK WORKER ---
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark_worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_OPTS=--packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
